version: "3.8"

# Define a custom network for your services
networks:
  my_network:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - my_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - my_network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    networks:
      - my_network

  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - my_network
